version: '3'

services:
  app:
    image: adriangl/tomcat-sgved:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - sgved
  caddy:
    image: caddy:2.3.0-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - sgved
networks:
  sgved:
    driver: bridge