version: '3'

services:
  sgved-java:
    image: adriangl/sgved-java:latest
    container_name: sgved-java
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - sgved
  sgved-caddy:
    container_name: sgved-caddy
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - sgved
networks:
  sgved:
    driver: bridge